"use client"

import * as React from "react"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/layout/app-sidebar"
import { ThemeToggle } from "@/components/theme-toggle"
import { Separator } from "@/components/ui/separator"
import { AlertCircle, Bell, Clock, ShieldAlert, CheckCircle2 } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export default function AlertsPage() {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center justify-between gap-2 px-6 border-b border-border/50 sticky top-0 bg-background/80 backdrop-blur-md z-10">
          <div className="flex items-center gap-2">
            <SidebarTrigger className="-ml-1" />
            <Separator orientation="vertical" className="mr-2 h-4" />
            <div className="flex items-center gap-2">
              <span className="font-headline font-bold text-lg tracking-tight uppercase">Security & Anomaly Alerts</span>
            </div>
          </div>
          <ThemeToggle />
        </header>

        <main className="p-6 space-y-6">
          <div className="flex items-center justify-between">
            <div className="space-y-1">
              <h2 className="text-2xl font-bold font-headline tracking-tight">Active Notifications</h2>
              <p className="text-muted-foreground text-sm">Real-time alerts generated by the probabilistic drift detection system.</p>
            </div>
            <Button variant="outline" size="sm">
              <CheckCircle2 className="h-4 w-4 mr-2" /> Mark all read
            </Button>
          </div>

          <div className="space-y-4">
            {[
              { 
                id: 1, 
                title: "Significant Distribution Shift", 
                desc: "Feature 'SalaryCycle' in Nigeria cluster has drifted by 0.12 MAE over the last 6 hours.", 
                time: "12 mins ago", 
                type: "Drift", 
                severity: "high" 
              },
              { 
                id: 2, 
                title: "Linguistic Model Retraining Required", 
                desc: "Confidence score for Shona-Slang dialect has dropped below 0.85 threshold.", 
                time: "2 hours ago", 
                type: "Performance", 
                severity: "medium" 
              },
              { 
                id: 3, 
                title: "Endpoint Latency Spike", 
                desc: "v3/infra/load-projector is experiencing 400ms+ latency in the Nairobi region.", 
                time: "4 hours ago", 
                type: "Infrastructure", 
                severity: "high" 
              },
              { 
                id: 4, 
                title: "Unauthorized Token Rotation Attempt", 
                desc: "An attempt to rotate the primary API key was blocked from an unrecognized IP.", 
                time: "Yesterday", 
                type: "Security", 
                severity: "medium" 
              },
            ].map((alert) => (
              <Card key={alert.id} className="glass-panel hover:border-primary/50 transition-colors">
                <CardContent className="p-4">
                  <div className="flex items-start gap-4">
                    <div className={`p-2 rounded-full mt-1 ${alert.severity === 'high' ? 'bg-accent/10 text-accent' : 'bg-primary/10 text-primary'}`}>
                      {alert.severity === 'high' ? <ShieldAlert className="h-5 w-5" /> : <Bell className="h-5 w-5" />}
                    </div>
                    <div className="flex-1 space-y-1">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className="font-bold text-lg font-headline">{alert.title}</span>
                          <Badge variant={alert.severity === 'high' ? 'destructive' : 'secondary'} className="text-[10px] uppercase tracking-tighter">
                            {alert.type}
                          </Badge>
                        </div>
                        <div className="flex items-center text-xs text-muted-foreground gap-1">
                          <Clock className="h-3 w-3" />
                          {alert.time}
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {alert.desc}
                      </p>
                      <div className="pt-2 flex gap-2">
                        <Button size="sm" variant="secondary" className="h-8 text-[11px] font-bold">Investigate Root Cause</Button>
                        <Button size="sm" variant="ghost" className="h-8 text-[11px]">Ignore</Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </main>
      </SidebarInset>
    </SidebarProvider>
  )
}
